### ISSUE TITLE
Adding a BlockIP entry

### ISSUE THREAD

**Issue by mdjekic** [ChrisAlvares/node-adwords#11]
Kudos for a good library. I'm trying to create a block IP criterion for a campaign and it's failing with the following error:

`"Fault": {
"faultcode": "soap:Client",
"faultstring": "Unexpected wrapper element mutate found.   Expected {https://adwords.google.com/api/adwords/cm/v201609}mutate."
}`

I'm following the PHP library as advised and as a matter of fact have a working implementation of the same functionality in PHP with the one difference - in PHP I'm instantiating a NegativeCampaignCriterion which I'm not able to do here since the lib is using a standard object notation. This is why this looks like an issue with the library itself.

These are the methods/entities used:
- https://developers.google.com/adwords/api/docs/reference/v201607/CampaignCriterionService#mutate
- https://developers.google.com/adwords/api/docs/reference/v201607/CampaignCriterionService.CampaignCriterionOperation
- https://developers.google.com/adwords/api/docs/reference/v201607/CampaignCriterionService.CampaignCriterion
- https://developers.google.com/adwords/api/docs/reference/v201607/CampaignCriterionService.IpBlock

Here's my implementation:

```
blockIp(accountNumber,campaignId,ip) {
    var _this = this;

    return _this.configure().then(function onApiConfigured() {
      // prepare
      var user = _this.prepareUser(accountNumber);
      var service = user.getService('CampaignCriterionService', _this.gapi.version);

      // build
      var criterion = {
        campaignId: campaignId,
        isNegative: true,
        criterion: { ipAddress: ip }
      };
      var operation = { operator: 'ADD', operand: criterion };

      // wrap the call in a promise
      return new Promise(function executeBlockIp(resolve,reject) {
        service.mutate([operation], function onBlockIpDone(err, result) {
          if(err) {
            reject({ message: 'Google API error', error: err });
          }
          else {
            resolve(result);
          }
        });
      });
    });
  }
```

Please note that `_this.prepareUser(accountNumber);` is working in other functionality implementations so there are no hidden problems, just the fact I seem to be failing at implementing this operation.

Can you advise? Needless to say I will appreciate a quick reply and assistance.

**Comment by mdjekic** [comment]
I have some new development here and I'm hoping that (1) we'll be able to solve this and (2) it will serve to someone else as documentation :)

First of all I've "solved" the error above simply by changing `service.mutate([operation]...` to `service.mutate({operations:[operation]}`. I just didn't expect something like this to work but..it sure does. I tried this after reading the docs again:
https://developers.google.com/adwords/api/docs/reference/v201607/CampaignCriterionService#mutate

The next error was an obviously a wrongly built criterion so I made the following change:
```
var criterion = {
    campaignId: campaignId,
    isNegative: true,
    criterion: {
        id: 1,
        type: 'IP_BLOCK',
        'Criterion.Type': 'IpBlock'
        //ipAddress: ip
    }
};
```

Notice that the ipAddress is commented out, if I don't do this I get the following error:
```
{
    "faultcode": "soap:Server",
    "faultstring": "[CampaignCriterionError.CONCRETE_TYPE_REQUIRED @ operations[0].operand.criterion]",
    ...
}
```

I'm thinking that the problem here is the lib is using standard object notation and there's some special sauce that the official (e.g. PHP) library adds when a specific criteria entity is instantiated (in this case the IpBlock).

If I make the call with `ipAddress: ip` commented out I get the following error: 
```
{
    "faultcode": "soap:Client",
    "faultstring": "Unmarshalling Error: cvc-complex-type.2.4.d: Invalid content was found starting with element 'ipAddress'. No child element is expected at this point.",
    ...
}
```

Although the folks back at Google say that that is a required field.

Any thoughts? Thanks!

**Comment by mdjekic** [comment]
BTW here's a piece of working PHP code:

```
<?php

function blockIp($ip,$campaignid,$customerId) {
  $user = new AdWordsUser();
  $user->SetClientCustomerId($customerId);
  $user->LogAll();

  $ipexclude = new IpBlock($ip,1,'IP_BLOCK','IpBlock');
  $campaignCriterionService = $user->GetService('CampaignCriterionService', 'v201609');

  $campaignCriterion = new NegativeCampaignCriterion();
  $campaignCriterion->campaignId=$campaignid;
  $campaignCriterion->criterion=$ipexclude;
  $campaignCriterion->isNegative=TRUE;

  $operation = new CampaignCriterionOperation();
  $operation->operator = 'ADD';
  $operation->operand=$campaignCriterion;
  $operation->OperationType='IP_BLOCK';

  $operations = array();
  $operations[] = $operation;
  $result = $campaignCriterionService->mutate($operations);
  return $result;
}
```

**Comment by mdjekic** [comment]
Additionally, here's a fully working example of **removing** the IP block using the lib:

```
  /**
   * Attempts to unblock an IP address for a campaign
   *
   * @param {String} accountNumber
   * @param {String} campaignId
   * @param {String} blockId
   * @return {Promise}
   */
  unblockIp(accountNumber,campaignId,blockId) {
    debug(`Unblocking IP address on campaign {$campaignId} for account number ${accountNumber}.`);
    var _this = this;

    return _this.configure().then(function onApiConfigured() {
      // prepare
      var user = _this.prepareUser(accountNumber);
      var service = user.getService('CampaignCriterionService', _this.gapi.version);

      // build
      var criterion = {
        campaignId: campaignId,
        isNegative: true,
        criterion: {
          id: blockId,
          type: 'IP_BLOCK',
          'Criterion.Type': 'IpBlock'
        },
        'CampaignCriterion.Type': 'NegativeCampaignCriterion'
      };
      var operation = { operator: 'REMOVE', operand: criterion };

      // wrap the call in a promise
      return new Promise(function executeBlockIp(resolve,reject) {
        service.mutate({operations: [operation]}, function onBlockIpDone(err, result) {
          if(err) {
            debug(`Error unblocking IP address.`);
            reject({ message: 'Google API error', error: err });
          }
          else {
            debug(`Successfully unblocked IP address.`);
            resolve();
          }
        });
      });
    });
  }
```

**Comment by ChrisAlvares** [comment]
hey @mdjekic, I'll have to take a look at this this weekend. Thanks for the code samples!

**Comment by Jonathanx5** [comment]
Should interest me too !!!

**Comment by ChrisAlvares** [comment]
fixed via #18

https://github.com/ChrisAlvares/node-adwords/blob/master/test/adwords/services/campaigncriterionservice.js#L56-L70

**Comment by tiagosot1** [comment]
Olá, eu aprendendo a Api do Adwords, gostaria de orientação de como configurar. Esta biblioteca está funcional? 

_**constructor(obj) {
        this.credentials = _.extend({
            developerToken: '',
            userAgent: 'node-adwords',
            clientCustomerId: '',
            client_id: '',
            client_secret: '',
            refresh_token: '',//@todo implement refesh token instead of access token
            access_token: '',
        }, obj);
}**_

preciso preencher todos os campos, eu tenho o developerToken e o Client_id.

**Comment by ChrisAlvares** [comment]
Yes, it is functional. There are a ton of examples inside the test folder: https://github.com/ChrisAlvares/node-adwords/blob/master/test/adwords/services

**Comment by tiagosot1** [comment]
Thank you, I'll study.

**Comment by Nastromo** [comment]
> Additionally, here's a fully working example of **removing** the IP block using the lib:
> 
> ```
>   /**
>    * Attempts to unblock an IP address for a campaign
>    *
>    * @param {String} accountNumber
>    * @param {String} campaignId
>    * @param {String} blockId
>    * @return {Promise}
>    */
>   unblockIp(accountNumber,campaignId,blockId) {
>     debug(`Unblocking IP address on campaign {$campaignId} for account number ${accountNumber}.`);
>     var _this = this;
> 
>     return _this.configure().then(function onApiConfigured() {
>       // prepare
>       var user = _this.prepareUser(accountNumber);
>       var service = user.getService('CampaignCriterionService', _this.gapi.version);
> 
>       // build
>       var criterion = {
>         campaignId: campaignId,
>         isNegative: true,
>         criterion: {
>           id: blockId,
>           type: 'IP_BLOCK',
>           'Criterion.Type': 'IpBlock'
>         },
>         'CampaignCriterion.Type': 'NegativeCampaignCriterion'
>       };
>       var operation = { operator: 'REMOVE', operand: criterion };
> 
>       // wrap the call in a promise
>       return new Promise(function executeBlockIp(resolve,reject) {
>         service.mutate({operations: [operation]}, function onBlockIpDone(err, result) {
>           if(err) {
>             debug(`Error unblocking IP address.`);
>             reject({ message: 'Google API error', error: err });
>           }
>           else {
>             debug(`Successfully unblocked IP address.`);
>             resolve();
>           }
>         });
>       });
>     });
>   }
> ```

Where did you get the id (blockId) in you criterion?
