### ISSUE TITLE
using OfflineConversionFeedService 

### ISSUE THREAD

**Issue by gilLionKing** [ChrisAlvares/node-adwords#13]
hi brother thanks for the package.  any chance you are attaching a small example of how to use 
this service ? i have looked at the php api example like here but couldn't get it to work.
$offlineConversionService = $user->GetService("OfflineConversionFeedService", API_VERSION);
$operations = array();
foreach ($conversions as $conversion) {
    $gclid = $conversion["gclid"];
    $convDate = date("Ymd His", $conversion["date"]);
    $convValue = isset($conversion["value"]) ? $conversion["value"] : 0;
    $offlineConversion = new OfflineConversionFeed(
            $gclid, $conversionName, $convDate, $convValue
    );
    $operations[] = new OfflineConversionFeedOperation($offlineConversion, "ADD");
}
$result = $offlineConversionService->mutate($operations);

thank you very much

**Comment by andersonba** [comment]
👍

**Comment by ChrisAlvares** [comment]
this is without testing, but this should get you closer to what you need:

```js
let user = new AdwordsUser({...});
let offlineConversionFeedService = user.getService('OfflineConversionFeedService', config.version);
let conversion = [/*your conversions here*/];
let operations = conversions.map((conversion) => {
     var gclid = conversion.gclid;
     var convDate = moment('YYYY-MM-DD His', conversion.date);
     var convValue = conversion.value || 0;
     return {
        operator: 'ADD',
        operand: {
              googleClickId: gclid,
              conversionName: 'Conversion Name',
              conversionTime: convDate,
              conversionValue: convValue,
              conversionCurrencyCode: 'USD'
        }
    }
});
offlineConversionFeedService.mutate({operations: operations}, (error, results) => {
    console.log(error, results);
}
```
