### ISSUE TITLE
Cannot install on Node 7.0.0

### ISSUE THREAD

**Issue by hungchai** [ChrisAlvares/node-adwords#15]
npm install node-adwords --save
npm WARN deprecated node-uuid@1.4.7: use uuid module instead

> ursa@0.9.4 install c:\xxx\node_modules\ursa
> node-gyp rebuild

c:\xxx\node_modules\ursa>if not defined npm_config_node_gyp (node "c:\xxx\nvm\v7.0.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuil
d )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  ursaNative.cc
  win_delay_load_hook.cc
LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win32\lib\libeay32.lib' [c:\xxx\node_modules\ursa\build\ursaNative.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit c:\xxx\nvm\v7.0.0\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" c:\xxx\\nvm\\v7.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\xxx\node_modules\ursa
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
c:\xxx
`-- node-adwords@201609.0.2

npm WARN si-sem-advertise-api@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 (node_modules\ursa):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by ChrisAlvares** [comment]
That is an issue with your machine and node-gyp, you need to fix that first. I do not own a windows machine to help you out here, but on unix there are some python libs you have to install for node-gyp.

**Comment by hungchai** [comment]
After I removed all files from $HOME/.node-gyp. It is alright now, thanks
