### ISSUE TITLE
Adding Predicates to GET operations 

### ISSUE THREAD

**Issue by deearcodes** [ChrisAlvares/node-adwords#17]
I have the following code:
```
function getAdGroup (req, res) {
  let user = new AdwordsUser(adwordsConfig)
  let { campaignId } = req.body

  let adGroupService = user.getService('AdGroupService', 'v201609')
  let selector = {
    fields: ['Id', 'Name'],
    ordering: [{field: 'Name', sortOrder: 'ASCENDING'}],
    predicates: [{field: 'CampaignId', operator: 'EQUALS', values: [Number.parseInt(campaignId)]}],
    paging: {startIndex: 0, numberResults: AdwordsConstants.RECOMMENDED_PAGE_SIZE}
  }
  adGroupService.get({serviceSelector: selector}, (error, result) => {
    if (error) {
      return res.status(404).json(error)
    }
    return res.status(200).json(result)
  })
}
```

Getting this error:

` "Unmarshalling Error: cvc-complex-type.2.4.d: Invalid content was found starting with element 'predicates'. No child element is expected at this point."`

Anyone knows how to add predicates to selectors? I have tried using variations in the key: predicate/predicates and assigning array and non array values. 

Any help is really appreciated.

**Comment by deearcodes** [comment]
Problems where:
- the order in the selector object keys:
```
let selector = {
    fields: ['Id', 'Name', 'CampaignId'],
    predicates: [{field: 'CampaignId', operator: 'EQUALS', values: [Number.parseInt(campaignId)]}],
    ordering: [{field: 'Name', sortOrder: 'ASCENDING'}],
    paging: {startIndex: 0, numberResults: AdwordsConstants.RECOMMENDED_PAGE_SIZE}
  }
```
Also the values should be Number as campaignId field type is INT.

**Comment by ChrisAlvares** [comment]
Yeah, I am not sure why the adwords library requires the fields to be in a specific order, but for some reason it does :/

**Comment by deearcodes** [comment]
@ChrisAlvares Google must have super strict schemas so everything is tidy and clean. I think it's because of how the selector gets parsed in a query by the service.
