### ISSUE TITLE
TrafficEstimatorService criteria problem

### ISSUE THREAD

**Issue by talha-asad** [ChrisAlvares/node-adwords#22]
Given the below selector:
```js
{
          selector: {
            campaignEstimateRequests: [
              {
                adGroupEstimateRequests: [
                  {
                    keywordEstimateRequests: [
                      {
                        keyword: {
                          text: 'mars cruise',
                          matchType: 'BROAD'
                        }
                      },
                      {
                        keyword: {
                          text: 'cheap cruise',
                          matchType: 'BROAD'
                        }
                      }
                    ],
                    maxCpc: {
                      microAmount: 1000000
                    }
                  }
                ],
                criteria: [
                  {
                    'xsi:type': 'cm:Language',
                    id: 1000
                  },
                  {
                    'xsi:type': 'cm:Location',
                    id: 2840
                  }
                ]
              }
            ],
            platformEstimateRequested: true
          }
        }
```

Notice the `cm:` prefix in the `xsi:type` of criteria, this is necessary because the namespace is different. If this is removed the request fails with the following error:

```soap:Client: Unmarshalling Error: cvc-elt.4.2: Cannot resolve 'Language' to a type definition for element 'criteria'.```

I found the problem by observing the namespaces that were being sent. I think the library should be able to figure out the namespace automatically, thoughts?

**Comment by ChrisAlvares** [comment]
Most types do not require a `cm` prefix to them. Not sure why the traffic estimator service is different.

We use the node-soap sdk internally, so it handles all of the bindings there. I can create a test for the targeting idea service so that people can see the `cm` prefix if that helps.

**Comment by talha-asad** [comment]
Yes seems like a good idea.

**Comment by ChrisAlvares** [comment]
This has been fixed in the latest release. See https://github.com/ChrisAlvares/node-adwords#adwordstypes

**Comment by Chris911** [comment]
Even with the latest release I had to prefix the `xsi_type` with `cm:` for the request to work. I'm also using the TrafficEstimator service.
