### ISSUE TITLE
Maximum call stack size exceeded on a service

### ISSUE THREAD

**Issue by khawtf** [ChrisAlvares/node-adwords#25]
```
function createFeedItems(feed) {
	var feedItemService = AdWordUser.getService('FeedItemService', 'v201609');
	var feedId = feed.feedId;

	var attributes = [{
		feedAttributeId: "1",
		stringValue: "testname"
	},{
		feedAttributeId: "2",
		stringValue: "testprice"
	},{
		feedAttributeId: "3",
		stringValue: "testdate"
	}];

	// create feedItem with created attributes
	var feedItem = createFeedItem(feedId, attributes, target);
	
	let op = {
		operator: "ADD",
		operand: feedItem //filling in null returns same error
	}
	
	try {
	feedItemService.mutate({ operations: [op] }, feedItemsCreated);
	
	}catch(error){
		console.log(error);
	}
}
```

So i am debugging this for the whole day but it always returns the following error:
node_modules/soap/lib/wsdl.js:1924
WSDL.prototype.findChildSchemaObject = function(parameterTypeObj, childName) {
                                               ^RangeError: Maximum call stack size exceeded

As you can see even if i fill in null it returns the callstack error.

**Comment by ChrisAlvares** [comment]
Can you console out the `op` variable? That usually happens whenever you have a recursive object inside your operation.

**Comment by khawtf** [comment]
[IMG]http://i68.tinypic.com/14eawt1.png[/IMG]

**Comment by ChrisAlvares** [comment]
That link doesn't work. You can just drag and drop the image to the comment box

**Comment by khawtf** [comment]
<img width="1920" alt="schermafbeelding 2017-02-11 om 00 43 58" src="https://cloud.githubusercontent.com/assets/5428261/22851768/86542afa-f02c-11e6-9c4c-f4ac417f7ba7.png">

**Comment by khawtf** [comment]
Still can't find the solution :\

**Comment by khawtf** [comment]
I couldnt find the issue. I will revert back to the official php SDK

**Comment by naysumyat** [comment]
i am getting the same issue when i tried FeedItem Service. the other service has no issue. have you solved the issue ?

**Comment by naysumyat** [comment]
@ChrisAlvares @khawtf  ... I just fixed the issue  by updating  node-soap  library to latest version **Version 0.19.2**
please update it. 
thanks

**Comment by ChrisAlvares** [comment]
This has been fixed, thanks for being on the lookout @naysumyat
