### ISSUE TITLE
Cannot create expanded text ad

### ISSUE THREAD

**Issue by getupandgo** [ChrisAlvares/node-adwords#37]
Hello!
I'm trying to create ExpandedTextAd following official python [examples](https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201702/basic_operations/add_expanded_text_ads.py).
So far i've created such method for creating ad:
```
function createAdGroupAd(adGroup, appearance) {
  const newAd = {
    'xsi:type': 'AdGroupAd',
    adGroupId: adGroup.id,
    ad: {
      'xsi:type': 'ExpandedTextAd',
      headlinePart1: appearance.headLine1,
      headlinePart2: appearance.headLine2,
      description: appearance.linkDescription,
      path1: appearance.path1,
      path2: appearance.path2,
      finalUrls: [
        'http://www.example.com/cruise/space/',
        'http://www.example.com/locations/mars/'
      ]
    },
    status: 'PAUSED'
  }

  const adOperation = {
    operator: 'ADD',
    operand: newAd
  }

  return adGroupAdService.mutateAsync({ operations: [adOperation] })
}
```
Where adGroup is sucessfully created adGroup.
But i'm getting such error: 

```Error: soap:Client: Unmarshalling Error: cvc-complex-type.2.4.d: Invalid content was found starting with element 'finalUrls'. No child element is expected at this point.```
Any idea what can it be?

**Comment by srn** [comment]
Try using `xsi_type` instead of `xsi:type`.

**Comment by getupandgo** [comment]
Already tried this.
Got the ``` Error: soap:Client: Unmarshalling Error: cvc-complex-type.2.4.a: Invalid content was found starting with element 'xsi_type'``` error.

**Comment by srn** [comment]
Right, I just noticed this: https://github.com/ChrisAlvares/node-adwords/blob/master/lib/request-parser.js#L38-L42

What if you're using just a single url in the `finalUrls` list? Try:

```js
finalUrls: ['http://www.example.com/cruise/space/']
```

**Comment by getupandgo** [comment]
Got the same ```  Error: soap:Client: Unmarshalling Error: cvc-complex-type.2.4.d: Invalid content was found starting with element 'finalUrls'. No child element is expected at this point. ```

**Comment by getupandgo** [comment]
Finally solved it!
Basically, you must provide fields in correct order, like in [doc](https://developers.google.com/adwords/api/docs/reference/v201702/AdGroupAdService.ExpandedTextAd); i.e. finalUrls must be first field.
So, for ExpandedTextAd correct object will look like this:

```
const ad = {
     finalUrls: [appearance.finalUrls],
     headlinePart1: appearance.headlinePart1,
     headlinePart2: appearance.headlinePart2,
     description: appearance.description,
     path1: appearance.path1,
     path2: appearance.path2,
    'xsi:type': 'ExpandedTextAd'
} ```

I think to add an example when I will have more free time

**Comment by ChrisAlvares** [comment]
Yup, this is an issue #20
