### ISSUE TITLE
Publish release?

### ISSUE THREAD

**Issue by rosslavery** [ChrisAlvares/node-adwords#38]
Hi there,

First off, thanks for the great work on this. I'd appreciate it if you could publish a new release containing 506f63888bb48d7aba2c21b4094e1d8026eaa074 to npm, as we're looking to run some reports using the new date range functionality.

Installing from master for now, but an npm release would be great.

**Comment by ChrisAlvares** [comment]
Ah, yes sorry totally forgot about that. Will publish tomorrow when I am back from travels.

**Comment by rosslavery** [comment]
Awesome, thanks! I'll leave this open for you then.

**Comment by ChrisAlvares** [comment]
Published. I will also be updating to 201705 by EOW so you can use that as well.

**Comment by rosslavery** [comment]
Amazing, thank you!
