### ISSUE TITLE
Cannot create feed items from api 

### ISSUE THREAD

**Issue by naysumyat** [ChrisAlvares/node-adwords#42]
i have been trying for 2 days  to be able to create Feed Items from api but without success. it looks like feed item format is not correct. the error that i am getting currently is :
 if ((childNsURI.match("http://schemas.microsoft.com") === null) || isInsideSchemaMS) {
                      ^ RangeError: Maximum call stack size exceeded
and below is my code...

        ` let attributes = [
                    {feedAttributeId:1,stringValue:"my awesome site "},
                    {feedAttributeId:5,stringValues:["http://www.google.com/about"]}
                ];
        let feedItem = {
            feedId:55897084,//site link feed 
            status: 'UNKNOWN',
            attributeValues: attributes
        };

        let feedOperation = {
            operator: 'ADD',
            operand: feedItem
        };

        try {

          feedItemService.mutate({operations:[feedOperation]}, (error, Result) => {
            console.log("done");
            console.log(Result);
            console.log(error);
          });

        }catch(err){
          console.log(err);
        }`
please kindly help

**Comment by naysumyat** [comment]
checked the test folder too  to see any example but could not find.

**Comment by ChrisAlvares** [comment]
Closing in favor of #25.

I am going to look into this guy when I have a chance, but it has to do with a bug in the `node-soap` library. Not sure there is much I can do about this without switching to something more maintained.
