### ISSUE TITLE
TargetingIdeaService error

### ISSUE THREAD

**Issue by Madses** [ChrisAlvares/node-adwords#43]
I have been trying to get this code to work but i have no idea why its still not working, could you please help me out?

var TargetingIdeaService = user.getService('TargetingIdeaService', 'v201609')

//create selector 
var selector={
    SearchParameter:[{RelatedToQuerySearchParameter:'Games'}],
    IdeaType:'KEYWORDS',
    requestType:'IDEAS',
    requestedAttributeTypes: ['TARGETED_MONTHLY_SEAsRCHES', 'KEYWORD_TEXT'],
    paging: {startIndex: 0, numberResults:20}
}
 
TargetingIdeaService.get({serviceSelector: selector}, function (error, result) {
    console.log(error, result);
})

**Comment by Madses** [comment]
var TargetingIdeaService = user.getService('TargetingIdeaService', 'v201609')

//create selector 
var selector={
    searchParameters:[{
    	xsi_type: 'RelatedToQuerySearchParameter',
    	queries: ['donald trump'],
    }],
    ideaType:'KEYWORD',
    requestType:'STATS',
    requestedAttributeTypes:['KEYWORD_TEXT'],
    paging: {startIndex: 0, numberResults:20}
}
 
TargetingIdeaService.get({TargetingIdeaSelector: selector}, function (error, result) {
    console.log(error, result);
}) 
 Updated

**Comment by ChrisAlvares** [comment]
What is the error you are getting?

There is a sample for the targeting idea service [here](https://github.com/ChrisAlvares/node-adwords/blob/master/test/adwords/services/targetingideaservice.js)

**Comment by Madses** [comment]
I just wanted to let u know that your example was really helpful, thanks! The issue was 👍 
TargetingIdeaSelector:selector had to be selector:selector
