### ISSUE TITLE
ConstantDataService does not work

### ISSUE THREAD

**Issue by gi4c0** [ChrisAlvares/node-adwords#44]
I tried to get list of existing languages with ConstantDataService but got nothing. It doesn't return error nor result. What am I doing wrong?
`const AdwordsUser = require('node-adwords').AdwordsUser
const adwordsApiUser = new AdwordsUser(config.get('services.adwords.user')) //correct user data
const constantDataService = adwordsApiUser.getService('ConstantDataService', config.get('services.adwords.version'))

constantDataService.getLanguageCriterion((err, result) => console.log(err, result)`

**Comment by ChrisAlvares** [comment]
The first parameter is not the callback, it is the object request parameters.

**Comment by gi4c0** [comment]
It is strange because there is no object request parameters in the docs. But now it works. Thanks.
