### ISSUE TITLE
TypeError: uuid.v4 is not a function

### ISSUE THREAD

**Issue by felipegarcia92** [ChrisAlvares/node-adwords#46]
Hello there!
Thanks for sharing the library :)

I'm trying to fetch an accounts list from my customers, but I'm receiving this error upon every request to the Adwords API:

```
.../node_modules/soap/lib/client.js:275
  var eid = options.exchangeId || uuid.v4();
                                       ^

TypeError: uuid.v4 is not a function
```

Do you have any idea of how can I solve this? Tried changing my `uuid` version on my `packages.json` but didn't do the trick, still getting it.

**Comment by ChrisAlvares** [comment]
This seems to be an issue with the `node-soap` library. Can you post the method you are trying to use?

**Comment by felipegarcia92** [comment]
Thanks for responding Chris!
Here's what I'm trying to achieve:

```
router.post('/google-code', (req, res) => {
  const code = req.body.code;

  const auth = new AdwordsAuth({
    client_id: process.env.ADWORDS_OAUTH2_CLIENT_ID,
    client_secret: process.env.ADWORDS_OAUTH2_SECRET,
  }, 'http://localhost:3333');

  auth.getAccessTokenFromAuthorizationCode(code, (error, tokens) => {
    const credentials = {
      developerToken: 'bqP8izsBmM7NusJ87Yttuw',
      client_id: process.env.ADWORDS_OAUTH2_CLIENT_ID,
      client_secret: process.env.ADWORDS_OAUTH2_SECRET,
      refresh_token: tokens.refresh_token,
      access_token: tokens.access_token,
    };

    const user = new AdwordsUser(credentials);
    console.log(user);
    const customerService = user.getService('CustomerService', 'v201705');
    console.log(customerService);

    customerService.getCustomers((err, result) => {
      console.log(err, result);
    });

    res.sendStatus(200);
  });
});
```

**Comment by ChrisAlvares** [comment]
Please don't send your developer token in the sample. I have removed it, but you might want to change it.

**Comment by ChrisAlvares** [comment]
Also, the first parameter of the getCustomers needs to be an object, not a callback. 

```js
customerService.getCustomers({}, () => {

});
```

That should work.

**Comment by felipegarcia92** [comment]
@ChrisAlvares thanks for removing the token, my bad!

Changed that, thank you! But still receiving that error. As you said, it looks like an issue with another dependency.

**Comment by felipegarcia92** [comment]
After a day of struggling a simple `rm -fr node_modules && npm install` fixed the issue. My bad.

Closing!

**Comment by felipegarcia92** [comment]
Having done that and worked locally, when going to production to Heroku, it's not trivial nor desired to do that. 

If you visit https://github.com/vpulim/node-soap/pull/913#issuecomment-321300974 you'll notice they realized they had an error, they fixed and merged it, but still haven't got to a release. 

I needed it now, so I forked the repo and pointed the soap library to that specific commit, you can check it out here: https://github.com/felipegarcia92/node-adwords/blob/master/package.json

And it did work. May be useful for you too.

**Comment by antoniosthanasisgit** [comment]
uuid.v4(); change this to this uuid.v4; and also import 
import {v1 as uuid} from "uuid"; 
// import {v3 as uuid} from "uuid"; 
// import {v4 as uuid} from "uuid"; 
// import {v5 as uuid} from "uuid";

**Comment by vikashsinghcse** [comment]
> change this uuid.v4(); to this uuid.v4; and also
> import {v4 as uuid} from "uuid";

It worked for me.

**Comment by vikashsinghcse** [comment]
`import { v4 as uuidv4 } from 'uuid';
uuidv4();`

**Comment by Abdaljawad-Ayah** [comment]
> `import { v4 as uuidv4 } from 'uuid';`
> `uuidv4();`

thank you it helped me i was stuck at something

**Comment by janacm** [comment]
For other Typescript newbies like me that want to understand why this is happening - [see here](https://janac.medium.com/typeerror-uuid-v4-is-not-a-function-e70a1084208). It's because `v4()` is being exported, so we need to `import` it, rather than try to access it via a `.` operator.

**Comment by m-r-q-w-e-r-t-y** [comment]
> change this uuid.v4(); to this uuid.v4; and also
> import {v4 as uuid} from "uuid";

This helped me. Thanks!

**Comment by RafaelJP13** [comment]
Check the name of the package in the package.json and imports/requires.
