### ISSUE TITLE
Error in browser(chrome,firefox) TypeError: fs.readdirSync is not a function

### ISSUE THREAD

**Issue by aboobakkar** [ChrisAlvares/node-adwords#52]
i am trying to 'node adwords' on meteor framework, then type error in browser fs.readdirSync is not a function

**Comment by ChrisAlvares** [comment]
@aboobakkar - you should not use this library on the client side. You are going to expose your client id, secret and developer token to the world. If a user gets access to these, your google account can become compromised and your google account can be billed for someone else's API usage.
