### ISSUE TITLE
AuthorizationError.SERVICE_ACCESS_DENIED

### ISSUE THREAD

**Issue by HelloKevinTian** [ChrisAlvares/node-adwords#63]
HI
I tried to get google adwords report with node-adwords, and arguments like **developerToken,userAgent,clientCustomerId,client_id,client_secret,refresh_token** are correct in my MCC account.
I am an administrator in MCC account and has a high-level credentials.
Howerev I still met the error **AuthorizationError.SERVICE_ACCESS_DENIED**.

I want to know why it is. Please help me out. Thanks.

**Comment by ChrisAlvares** [comment]
That error typically means your developer token is not valid.

**Comment by HelloKevinTian** [comment]
The reason why this happended is that the develop_token was not granted the proper permissions by Google official. Now it has been solved.
