### ISSUE TITLE
Uploading Image for a Display Ad

### ISSUE THREAD

**Issue by bryanlvenable** [ChrisAlvares/node-adwords#66]
I'm attempting to upload an image to use as a display ad. Below is my function, which when called returns an error with message "soap:Client: [MediaError.UNSUPPORTED_TYPE @ media[0]]". I believe the structure I am using for `media` and `operations` is incorrect, but I am not sure what to use. I have tried many things and the docs haven't been very helpful. Any help is appreciated.

```
const mediaService = user.getService('MediaService');

const uploadImage = async (url) => {
  return new Promise((resolve, reject) => {
    const media = {
      type: 'IMAGE',
      urls: {
        key: 'FULL',
        value: url
      }
    };

    const operations = {
      media
    };

    mediaService.upload(operations, (err, result) => {
      if (err) {
        console.error(err);
        reject(err);
      }
      resolve(result.value);
    });
  });
};
```
Link to docs that identify `IMAGE` as an acceptable value of `type`: https://developers.google.com/adwords/api/docs/reference/v201802/AdGroupAdService.Media

**Comment by bryanlvenable** [comment]
I figured it out, my issue was that I was specifying `xsi:type` wrong on earlier attempts which led me down this wrong path. The troubleshooting section of the README helped me out. Thanks for the awesome library.

**Comment by actuallymentor** [comment]
> I figured it out, my issue was that I was specifying xsi:type wrong on earlier attempts

Could you detail exactly what you did wrong and how you got it working?

Thank you!
