### ISSUE TITLE
Error of auth.js

### ISSUE THREAD

**Issue by firstguo** [ChrisAlvares/node-adwords#67]
File:  adwords/auth.js
in line 2: 
var OAuth2 = google.auth.OAuth2;

In fact there should be 
var OAuth2 = google.google.auth.OAuth2;

**Comment by c0bra** [comment]
Same issue as what you'll find here:

https://github.com/gsuitedevs/node-samples/issues/6
https://stackoverflow.com/questions/49866493/google-oauth-typeerror-cannot-read-property-oauth2-of-undefined
https://stackoverflow.com/questions/49848105/google-drive-api-cannot-read-property-oauth2-of-undefined?noredirect=1&lq=1

**Comment by c0bra** [comment]
Actually looks like this is fixed with `201802.3.0`
