### ISSUE TITLE
A way to implement segments

### ISSUE THREAD

**Issue by cesardmoro** [ChrisAlvares/node-adwords#71]
Looking for a way to implement segmentatión.

We want to get daily reports in a range of dates. 
Trying to use segments:

https://developers.google.com/adwords/api/docs/appendix/reports/campaign-performance-report#date

But no find documentation for nodejs.

**Comment by ChrisAlvares** [comment]
See https://github.com/ChrisAlvares/node-adwords/blob/master/test/adwords/services/reporting.js#L19-L30
