### ISSUE TITLE
create campaign

### ISSUE THREAD

**Issue by shlomioz** [ChrisAlvares/node-adwords#74]
Hello all,

I am trying to create a new campaign with the API, and I get this error:
"Client: Unmarshalling Error: cvc-complex-type.2.4.a: Invalid content was found starting with element 'budget'......."
I understand from other issues that this problem is about the order of the object.
this is the object that I am trying to use:
{
        operations: [{
            operator: 'ADD',
            operand: {
                name: "masho",
                status: "PAUSED",
                advertisingChannelType: 'SEARCH',
                biddingStrategyConfiguration: {
                    biddingStrategyType: 'MANUAL_CPC'
                },
                budget: {
                    budgetId: 2085008246 //this is a budgetId that i create before (tried as string and as a number) .
                }
            }
        }]
    }

Can anyone tell me what is the problem? I am trying to solve this for hours.
And also, there is anyone knows where can I find an example for every request order?

thanks,
Shlomi

**Comment by nicoespeon** [comment]
Hi @shlomioz 👋 

I don't know if you solved your issue, but it looks like an ordering issue: https://github.com/ChrisAlvares/node-adwords#ordering

In short, AdWords API is SOAP, so the order of properties in your request matters. The order that works should be the one of the documentation (e.g. [for Campaigns](https://developers.google.com/adwords/api/docs/reference/v201806/CampaignService.Campaign)).

This should work:

```js
{
  operations: [
    {
      operator: 'ADD',
      operand: {
        name: 'masho',
        status: 'PAUSED',
        budget: {
          budgetId: 2085008246 //this is a budgetId that i create before (tried as string and as a number) .
        }
        advertisingChannelType: 'SEARCH',
        biddingStrategyConfiguration: {
          biddingStrategyType: 'MANUAL_CPC'
        }
      }
    }
  ];
}
```

**Comment by ChrisAlvares** [comment]
Thanks @nicoespeon!
