### ISSUE TITLE
any valid documentation?

### ISSUE THREAD

**Issue by arielzadi** [ChrisAlvares/node-adwords#9]
hi i tried to create a campaign, budget ad etc..
problem is even after using php library as a reference i cant manage to do so.
any where i can see examples?

**Comment by ChrisAlvares** [comment]
Use the test folder and see some examples in there.

**Comment by arielzadi** [comment]
all i can see are tests for reports
so if anyone has an example for creating a campaign , adgroup, keywords and ads i would appreciate it.
up until now i have been using the java sdk for doing all of that and i am trying to migrate to node.

**Comment by ChrisAlvares** [comment]
I'll reopen this to add some documentation for how to create a campaign / adgroup.

**Comment by arielzadi** [comment]
any updates?

**Comment by EZGAMER** [comment]
Just picked up the library- Also looking into campaign building etc. Any luck or working examples? @arielzadi @ChrisAlvares

**Comment by ChrisAlvares** [comment]
@EZGAMER I added tests for campaign / adgroup / keywords:

campaign: https://github.com/ChrisAlvares/node-adwords/blob/master/test/adwords/services/campaignservice.js#L53-L71

adgroup: https://github.com/ChrisAlvares/node-adwords/blob/master/test/adwords/services/adgroupservice.js#L49-L71

keyword: https://github.com/ChrisAlvares/node-adwords/blob/master/test/adwords/services/adgroupcriterionservice.js#L49-L68
