### ISSUE TITLE
services.js service methods updated but a new module version not published in npmjs

### ISSUE THREAD

**Issue by laurynas-karvelis** [ChrisAlvares/node-adwords#96]
Hello,

really enjoying using this module. Been trying to call `customerService.getServiceLinks` method just to find out that it's simply not there in services.js service/method definition list.

Would it be possible to bump up this module's version and publish it onto npmjs for people to use methods that are defined in Google Ads v201809 version?

Thank you in advance!

**Comment by ChrisAlvares** [comment]
just published.
