### ISSUE TITLE
-

### ISSUE THREAD

**Issue by miguelurbina** [ChrisAlvares/node-adwords#98]

**Comment by samueljim** [comment]
bump

**Comment by chhatch** [comment]
I understand how confusing and frustrating get a refresh token can be. It depends on what application type you chose when you applied for credentials in the Google Developers Console. If it was 'Web Application', then try following [this guide](https://medium.com/@turhan.oz/oauth2-and-google-oauth-playground-550757f9355f) to get your refresh token from the Google Auth Playground.
